# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K83TQ8YYwE9oh2g6AAS6RXHlph_c09cI
"""

int(0.2467 * 12 + 4.159)